language: node_js
node_js:
- '0.12'
sudo: false
notifications:
  email: false
before_install:
- nvm install $NODE
- nvm use $NODE
before_script:
- npm prune
script: npm run $COMMAND
after_success:
- if [[ $COMMAND = test:coverage ]]; then npm run test:coverage:upload; fi
env:
  matrix:
  - NODE=0.10 COMMAND=test:browser:cloud
  - NODE=0.10 COMMAND=test:coverage
  - NODE=0.12 COMMAND=test
  - NODE=0.10 COMMAND=test
  - NODE=iojs-v1 COMMAND=test
  - NODE=iojs-v2 COMMAND=test
