sudo: false
language: node_js
notifications:
  email: false
node_js:
  - 4
before_script:
  - npm prune
script:
  - npm run $COMMAND
  - npm run lint
after_success:
  - npm run semantic-release
  - npm run test:coverage
  - npm run test:coverage:upload
env:
  matrix:
  - COMMAND=test
  - COMMAND=test:browser:cloud
branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
